### ISSUE TITLE
Yo Ur GitHub description wrong

### ISSUE THREAD

**Issue by halal-beef** [sonic011gamer/edk2-exynos7885#3]
I don't see no exynos 78845

![IMG_20230810_014447_762](https://github.com/sonic011gamer/edk2-exynos7885/assets/78730004/e63fc04f-e5b6-4284-82db-7e656d76568b)

**Comment by sonic011gamer** [comment]
Thanks, was originally going to name it edk2-exynos7884 but I realized it's exactly the same SoC as exy 7885
